name: Deploy trackTeacher front
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                persist-credentials: false

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                tools: 'composer:v2'

            - name: Setup database
              uses: mirromutth/mysql-action@v1.1
              with:
                mysql database: test
                mysql user: root
                mysql password: 123456

            - name: Install and testing
              env:
                CI: ""
              run: |
                composer require
                php artisan migrate --seed --force
                vendor/bin/phpunit

            - name: Deploy to heroku
              uses: akhileshns/heroku-deploy@v3.6.8
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: trackteacher
                heroku_email: cssuperpy@gmail.com
