name: Deploy trackTeacher front
on:
    push:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest

        services:
            mysql:
                image: mysql:5.7
                env:
                    MYSQL_ALLOW_EMPTY_PASSWORD: yes
                    MYSQL_DATABASE: test
                ports:
                    - 33306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1
              with:
                persist-credentials: false

            - name: Setup PHP with composer v2
              uses: shivammathur/setup-php@v2
              with:
                php-version: '7.4'
                tools: 'composer:v2'

            - name: Install app
              run: |
                cp .env.ci .env
                composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
                php artisan key:generate
                chmod -R 777 storage bootstrap/cache

            - name: Testing
              env:
                  DB_CONNECTION: mysql
                  DB_DATABASE: test
                  DB_PORT: 33306
                  DB_USER: root
                  DB_PASSWORD: ""
              run: |
                  php artisan migrate --seed
                  php artisan passport:install
                  php artisan test

            - name: Deploy to heroku
              uses: akhileshns/heroku-deploy@v3.6.8
              with:
                heroku_api_key: ${{secrets.HEROKU_API_KEY}}
                heroku_app_name: trackteacher
                heroku_email: cssuperpy@gmail.com
